[package]
name = "twinput"
version = "0.1.0"
authors = ["Robert Hawk <robert@the-hawk.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
